global using System;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.ComponentModel;
global using System.Collections;
global using System.Collections.Specialized;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Windows.Input;
global using Xamarin.Forms;
global using Xamarin.Forms.Internals;
global using Jakar.Extensions;
global using Jakar.Extensions.Attributes;
global using Jakar.Extensions.Collections;
global using Jakar.Extensions.Converters;
global using Jakar.Extensions.Exceptions;
global using Jakar.Extensions.FileSystemExtensions;
global using Jakar.Extensions.General;
global using Jakar.Extensions.Interfaces;
global using Jakar.Extensions.Models;
global using Jakar.Extensions.Models.Collections;
global using Jakar.Extensions.Models.Base;
global using Jakar.Extensions.Models.Base.Classes;
global using Jakar.Extensions.Models.Base.Records;
global using Jakar.Extensions.Models.Authorization;
global using Jakar.Extensions.Models.IniConfiguration;
global using Jakar.Extensions.Models.Users;
global using Jakar.Extensions.Http;
global using Jakar.Extensions.Languages;
global using Jakar.Extensions.Types;
global using Jakar.Extensions.Strings;
global using Jakar.Extensions.Xamarin.Forms;
global using Jakar.Extensions.Xamarin.Forms.Extensions;
global using Jakar.Extensions.Xamarin.Forms.MarkupExtensions;
global using Jakar.Extensions.Xamarin.Forms.Statics;
global using Jakar.Extensions.Xamarin.Forms.Converters;
global using Jakar.SettingsView.Shared;
global using Jakar.SettingsView.Shared.Config;
global using Jakar.SettingsView.Shared.Interfaces;
global using Jakar.SettingsView.Shared.Converters;
global using Jakar.SettingsView.Shared.sv;
global using Jakar.SettingsView.Shared.Misc;
global using Jakar.SettingsView.Shared.CellBase;
global using Jakar.SettingsView.Shared.Cells;
global using Jakar.SettingsView.Shared.Enumerations;
global using Jakar.SettingsView.Shared.Layouts;
global using Jakar.SettingsView.Shared.Layouts.Controls;
global using TypeConverterAttribute = Xamarin.Forms.TypeConverterAttribute;
global using Switch = Xamarin.Forms.Switch;
global using SwitchCell = Jakar.SettingsView.Shared.Cells.SwitchCell;
global using EntryCell = Jakar.SettingsView.Shared.Cells.EntryCell;
global using XfSwitchCell = Xamarin.Forms.SwitchCell;
global using XfEntryCell = Xamarin.Forms.EntryCell;
global using XfViewCell = Xamarin.Forms.ViewCell;
global using XfImageCell = Xamarin.Forms.ImageCell;
global using XfTextCell = Xamarin.Forms.TextCell;
global using Cell = Xamarin.Forms.Cell;
global using Jakar.SettingsView.Droid;
global using Jakar.SettingsView.Droid.Interfaces;
global using Jakar.SettingsView.Droid.BaseCell;
global using Jakar.SettingsView.Droid.Cells;
global using Jakar.SettingsView.Droid.Cells.Sources;
global using Jakar.SettingsView.Droid.Controls;
global using Jakar.SettingsView.Droid.Controls.Core;
global using Java.Lang;
global using Android.Runtime;
global using Android.App;
global using Android.Views;
global using Android.Text;
global using Android.Text.Format;
global using Android.Text.Method;
global using Android.Util;
global using Android.Widget;
global using Android.Content;
global using Android.Graphics;
global using Android.Graphics.Drawables;
global using Android.OS;
global using Android.Content.Res;
global using AndroidX.RecyclerView.Widget;
global using ACheckBox = Android.Widget.CheckBox;
global using Android.Views.InputMethods;
global using Jakar.Extensions.Xamarin.Forms.Droid.Extensions;
global using Xamarin.Forms.Platform.Android;
global using AContext = Android.Content.Context;
global using AView = Android.Views.View;
global using ALayout = Jakar.Extensions.Xamarin.Forms.Droid.Extensions.Layout;
global using Color = Xamarin.Forms.Color;
global using TextAlignment = Xamarin.Forms.TextAlignment;
global using Size = Xamarin.Forms.Size;
global using AColor = Android.Graphics.Color;
global using AObject = Java.Lang.Object;
global using AGridLayout = Android.Widget.GridLayout;
global using BaseCellView = Jakar.SettingsView.Droid.BaseCell.BaseCellView;
global using ARadioButton = Android.Widget.RadioButton;
global using PreserveAttribute = Xamarin.Forms.Internals.PreserveAttribute;
global using AListView = Android.Widget.ListView;
global using AButton = Android.Widget.Button;
global using ARelativeLayout = Android.Widget.RelativeLayout;
global using Orientation = Android.Widget.Orientation;
global using Math = System.Math;
global using Layout = Xamarin.Forms.Layout;
global using Enum = System.Enum;
global using Exception = System.Exception;
global using Debug = System.Diagnostics.Debug;
global using ARect = Android.Graphics.Rect;
global using Rect = Xamarin.Forms.Rect;
