global using System;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.ComponentModel;
global using System.Collections;
global using System.Collections.Specialized;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Windows.Input;
global using Xamarin.Forms;
global using Xamarin.Forms.Internals;
global using Jakar.Extensions;
global using Jakar.Extensions.Attributes;
global using Jakar.Extensions.Collections;
global using Jakar.Extensions.Converters;
global using Jakar.Extensions.Exceptions;
global using Jakar.Extensions.FileSystemExtensions;
global using Jakar.Extensions.General;
global using Jakar.Extensions.Interfaces;
global using Jakar.Extensions.Models;
global using Jakar.Extensions.Models.Collections;
global using Jakar.Extensions.Models.Base;
global using Jakar.Extensions.Models.Base.Classes;
global using Jakar.Extensions.Models.Base.Records;
global using Jakar.Extensions.Models.Authorization;
global using Jakar.Extensions.Models.IniConfiguration;
global using Jakar.Extensions.Models.Users;
global using Jakar.Extensions.Http;
global using Jakar.Extensions.Languages;
global using Jakar.Extensions.Types;
global using Jakar.Extensions.Strings;
global using Jakar.Extensions.Xamarin.Forms;
global using Jakar.Extensions.Xamarin.Forms.Extensions;
global using Jakar.Extensions.Xamarin.Forms.MarkupExtensions;
global using Jakar.Extensions.Xamarin.Forms.Statics;
global using Jakar.Extensions.Xamarin.Forms.Converters;
global using Jakar.SettingsView.Shared;
global using Jakar.SettingsView.Shared.Config;
global using Jakar.SettingsView.Shared.Interfaces;
global using Jakar.SettingsView.Shared.Converters;
global using Jakar.SettingsView.Shared.sv;
global using Jakar.SettingsView.Shared.Misc;
global using Jakar.SettingsView.Shared.CellBase;
global using Jakar.SettingsView.Shared.Cells;
global using Jakar.SettingsView.Shared.Enumerations;
global using Jakar.SettingsView.Shared.Layouts;
global using Jakar.SettingsView.Shared.Layouts.Controls;
global using PreserveAttribute = Xamarin.Forms.Internals.PreserveAttribute;
global using TypeConverterAttribute = Xamarin.Forms.TypeConverterAttribute;
global using Switch = Xamarin.Forms.Switch;
global using SwitchCell = Jakar.SettingsView.Shared.Cells.SwitchCell;
global using EntryCell = Jakar.SettingsView.Shared.Cells.EntryCell;
global using XfSwitchCell = Xamarin.Forms.SwitchCell;
global using XfEntryCell = Xamarin.Forms.EntryCell;
global using XfViewCell = Xamarin.Forms.ViewCell;
global using XfImageCell = Xamarin.Forms.ImageCell;
global using XfTextCell = Xamarin.Forms.TextCell;
global using Cell = Xamarin.Forms.Cell;
global using Color = Xamarin.Forms.Color;
global using TextAlignment = Xamarin.Forms.TextAlignment;
global using Size = Xamarin.Forms.Size;
global using Math = System.Math;
global using Layout = Xamarin.Forms.Layout;
global using Enum = System.Enum;
global using Exception = System.Exception;
global using Debug = System.Diagnostics.Debug;
global using Rect = Xamarin.Forms.Rect;
global using Jakar.SettingsView.iOS;
global using Jakar.SettingsView.iOS.Interfaces;
global using Jakar.SettingsView.iOS.Cells;
global using Jakar.SettingsView.iOS.Cells.Sources;
global using Jakar.SettingsView.iOS.BaseCell;
global using Jakar.SettingsView.iOS.Controls;
global using Jakar.SettingsView.iOS.Controls.HeaderFooter;
global using Jakar.SettingsView.iOS.Controls.Manager;
global using Jakar.SettingsView.iOS.Controls.Core;
global using UIKit;
global using Foundation;
global using CoreGraphics;
global using MobileCoreServices;
global using Xamarin.Forms.Platform.iOS;
global using Jakar.Extensions.Xamarin.Forms.iOS;
global using Jakar.Extensions.Xamarin.Forms.iOS.Enumerations;
global using Jakar.Extensions.Xamarin.Forms.iOS.Extensions;
global using Jakar.Extensions.Xamarin.Forms.iOS.Extensions.Layout;
global using Jakar.Extensions.Xamarin.Forms.iOS.Services;
global using PointF = CoreGraphics.CGPoint;
global using RectangleF = CoreGraphics.CGRect;
global using Stack = Jakar.SettingsView.iOS.Controls.Stack;
