global using System;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.ComponentModel;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Windows.Input;
global using Xamarin.Forms;
global using Jakar.Extensions;
global using Jakar.Extensions.Attributes;
global using Jakar.Extensions.Collections;
global using Jakar.Extensions.Converters;
global using Jakar.Extensions.Exceptions;
global using Jakar.Extensions.FileSystemExtensions;
global using Jakar.Extensions.General;
global using Jakar.Extensions.Interfaces;
global using Jakar.Extensions.Models;
global using Jakar.Extensions.Models.Collections;
global using Jakar.Extensions.Models.Base;
global using Jakar.Extensions.Models.Base.Classes;
global using Jakar.Extensions.Models.Base.Records;
global using Jakar.Extensions.Models.Authorization;
global using Jakar.Extensions.Models.IniConfiguration;
global using Jakar.Extensions.Models.Users;
global using Jakar.Extensions.Http;
global using Jakar.Extensions.Languages;
global using Jakar.Extensions.Types;
global using Jakar.Extensions.Strings;
global using Jakar.Extensions.Xamarin.Forms;
global using Jakar.Extensions.Xamarin.Forms.Extensions;
global using Jakar.Extensions.Xamarin.Forms.MarkupExtensions;
global using Jakar.Extensions.Xamarin.Forms.Statics;
global using Jakar.Extensions.Xamarin.Forms.Converters;
global using Jakar.SettingsView.Shared;
global using Jakar.SettingsView.Shared.Config;
global using Jakar.SettingsView.Shared.Interfaces;
global using Jakar.SettingsView.Shared.Converters;
global using Jakar.SettingsView.Shared.sv;
global using Jakar.SettingsView.Shared.Misc;
global using Jakar.SettingsView.Shared.CellBase;
global using Jakar.SettingsView.Shared.Cells;
global using Jakar.SettingsView.Shared.Enumerations;
global using Jakar.SettingsView.Shared.Layouts;
global using Jakar.SettingsView.Shared.Layouts.Controls;
global using TypeConverterAttribute = Xamarin.Forms.TypeConverterAttribute;
global using Switch = Xamarin.Forms.Switch;
global using SwitchCell = Jakar.SettingsView.Shared.Cells.SwitchCell;
global using EntryCell = Jakar.SettingsView.Shared.Cells.EntryCell;
global using XfSwitchCell = Xamarin.Forms.SwitchCell;
global using XfEntryCell = Xamarin.Forms.EntryCell;
global using XfViewCell = Xamarin.Forms.ViewCell;
global using XfImageCell = Xamarin.Forms.ImageCell;
global using XfTextCell = Xamarin.Forms.TextCell;
global using Cell = Xamarin.Forms.Cell;
